import type { Product, ProductCard, ProductQuery } from "@/lib/erp/types";

/*
 * The seam between the storefront and the ERP.
 *
 * Everything the site knows about the catalogue comes through this interface,
 * so the ERP can move — a different Supabase project, an HTTP API in front of
 * it, a different system entirely — without touching a page.
 *
 * What is deliberately NOT here: anything that writes stock. The ERP owns the
 * ledger. The storefront's job is to record what a customer asked for; turning
 * that into a stock movement is the ERP's, via post_sale(). See
 * lib/orders/convert.ts.
 */

export type StockLevel = {
  productId: string;
  /** Units physically on hand. */
  onHand: number;
  /** Claimed by open pre-orders. */
  reserved: number;
  /** onHand - reserved. What is actually free to promise. */
  available: number;
};

export type OrderDraftLine = {
  productId: string;
  sku: string;
  name: string;
  qty: number;
  /** Unit price at the moment of ordering. Snapshotted, never re-read. */
  unitPrice: number;
  isPreOrder: boolean;
};

export type OrderDraft = {
  /** Human-facing order number, e.g. HQ-24081. Generated by the storefront. */
  reference: string;
  customerName: string;
  customerPhone: string;
  customerAddress: string;
  lines: OrderDraftLine[];
  deliveryFee: number;
  /** Paid up front. 0 for plain COD, > 0 for a pre-order advance or deposit. */
  amountPaid: number;
  note: string | null;
};

export type CreatedOrder = {
  id: string;
  reference: string;
};

export interface ErpClient {
  /** The shop grid. Sorted and filtered server-side. */
  getProducts(query?: ProductQuery): Promise<ProductCard[]>;

  /** One product by its slug, for the PDP. null when there is no such slug. */
  getProduct(slug: string): Promise<Product | null>;

  /** Fresh stock for a set of products — used to re-check a cart at checkout. */
  getStock(productIds: string[]): Promise<StockLevel[]>;

  /**
   * Record a customer order. Returns as soon as the order is durable; pushing
   * it to the courier and posting it as an ERP sale are separate, later steps,
   * because a customer must never wait on a third-party API to see a
   * confirmation page.
   */
  createOrder(draft: OrderDraft): Promise<CreatedOrder>;

  /** Which implementation answered — surfaced in the admin footer, not to customers. */
  readonly source: "erp" | "mock";
}
