/* Generated by scripts/image-manifest.mjs — do not edit.
 * No photographs in public/products/ yet, so every image falls back to
 * Cloudinary if configured, and to the designed placeholder if not. */
export const LOCAL_IMAGES: Record<string, number[]> = {};
